# Generated by Django 4.2.7 on 2023-11-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colleague',
            options={'verbose_name': 'Colleague'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'Freelancer'},
        ),
        migrations.AddField(
            model_name='freelancer',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
