# Generated by Django 4.2.7 on 2023-11-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin'},
        ),
    ]
