# Generated by Django 4.2.7 on 2023-11-28 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_admin_options'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ManyToManyField(to='account.customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(to='account.admin'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='colleagues',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.FileField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workspace'),
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='colleague',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.ManyToManyField(to='account.admin'),
        ),
        migrations.AddField(
            model_name='task',
            name='colleagues',
            field=models.ManyToManyField(to='account.colleague'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='colleague',
            field=models.ManyToManyField(to='account.colleague'),
        ),
    ]
