# Generated by Django 4.2.7 on 2023-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_customer_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='finishing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_progress',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
