# Generated by Django 4.2.7 on 2023-12-20 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_taskcategory_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='colleagues',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finishing',
        ),
        migrations.RemoveField(
            model_name='task',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
