# Generated by Django 4.2.7 on 2023-12-20 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_colleagues_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
