# Generated by Django 4.2.7 on 2023-12-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_task_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
