# Generated by Django 4.2.7 on 2023-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_task_users_alter_task_category_assignedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedperson',
            name='user_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedperson',
            name='user_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
