# Generated by Django 4.2.7 on 2023-12-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_assignedperson_user_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPersonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.assignedperson',),
        ),
        migrations.CreateModel(
            name='TaskProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.task',),
        ),
    ]
