# Generated by Django 4.2.7 on 2023-12-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_assignedpersonproxy_taskproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedpersonproxy',
            options={'verbose_name': 'My Task', 'verbose_name_plural': 'My Tasks'},
        ),
    ]
