# Generated by Django 4.2.7 on 2023-12-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_assignedperson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedperson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
